services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tm470
      MYSQL_DATABASE: seasonality_db
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: secret123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment: 
      DATABASE_URL: mysql+pymysql://fastapi_user:secret123@mysql:3306/seasonality_db


volumes:
  mysql_data: