# fly.toml app configuration file generated for fastapi-mysql on 2025-09-08T18:20:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastapi-mysql'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3306
  force_https = false
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
